import { RPC, RPCMessageEvent } from 'rpc-shooter';
import { formatResponse } from '@/utils/response';

const ctx = self as unknown as { postMessage: (data: any) => void; onmessage: ((e: MessageEvent) => void) | null };

const rpc = new RPC({
  event: new RPCMessageEvent({
    currentEndpoint: ctx,
    targetEndpoint: ctx,
  }),
});

// Stub database functions - these will be implemented with full SQL operations
function createStubMethod(name: string) {
  return async (..._args: unknown[]) => {
    return formatResponse(null, 0, '');
  };
}

// Register all database methods
const methods = [
  'setSqlWasmPath',
  'initDB',
  'close',
  'getMessage',
  'getMultipleMessage',
  'getSendingMessageList',
  'updateMessageTimeAndStatus',
  'updateMessage',
  'updateMessageBySeq',
  'updateColumnsMessage',
  'insertMessage',
  'batchInsertMessageList',
  'getMessageList',
  'getMessageListNoTime',
  'messageIfExists',
  'searchMessageByKeyword',
  'searchMessageByContentType',
  'searchMessageByContentTypeAndKeyword',
  'updateMsgSenderFaceURLAndSenderNickname',
  'insertSendingMessage',
  'deleteSendingMessage',
  'getAllSendingMessages',
  'getAllConversationList',
  'getAllConversationListToSync',
  'getHiddenConversationList',
  'getConversation',
  'getMultipleConversation',
  'updateColumnsConversation',
  'decrConversationUnreadCount',
  'batchInsertConversationList',
  'insertConversation',
  'getTotalUnreadMsgCount',
  'batchUpdateConversationList',
  'clearAllConversation',
  'clearConversation',
  'conversationIfExists',
  'deleteConversation',
  'deleteAllConversation',
  'getConversationByUserID',
  'getConversationListSplit',
  'incrConversationUnreadCount',
  'removeConversationDraft',
  'resetAllConversation',
  'resetConversation',
  'setConversationDraft',
  'setMultipleConversationRecvMsgOpt',
  'unPinConversation',
  'getLoginUser',
  'insertLoginUser',
  'updateLoginUser',
  'getStrangerInfo',
  'setStrangerInfo',
  'getJoinedSuperGroupList',
  'getJoinedSuperGroupIDList',
  'getSuperGroupInfoByGroupID',
  'deleteSuperGroup',
  'insertSuperGroup',
  'updateSuperGroup',
  'deleteConversationUnreadMessageList',
  'batchInsertConversationUnreadMessageList',
  'getBlackList',
  'getBlackListUserID',
  'getBlackInfoByBlockUserID',
  'getBlackInfoList',
  'insertBlack',
  'deleteBlack',
  'updateBlack',
  'insertFriendRequest',
  'deleteFriendRequestBothUserID',
  'updateFriendRequest',
  'getRecvFriendApplication',
  'getSendFriendApplication',
  'getFriendApplicationByBothID',
  'getBothFriendReq',
  'insertGroup',
  'deleteGroup',
  'updateGroup',
  'getJoinedGroupList',
  'getGroupInfoByGroupID',
  'getAllGroupInfoByGroupIDOrGroupName',
  'subtractMemberCount',
  'addMemberCount',
  'getJoinedWorkingGroupIDList',
  'getJoinedWorkingGroupList',
  'getGroups',
  'batchInsertGroup',
  'deleteAllGroup',
  'insertGroupRequest',
  'deleteGroupRequest',
  'updateGroupRequest',
  'getSendGroupApplication',
  'insertAdminGroupRequest',
  'deleteAdminGroupRequest',
  'updateAdminGroupRequest',
  'getAdminGroupApplication',
  'insertFriend',
  'deleteFriend',
  'updateFriend',
  'getAllFriendList',
  'searchFriendList',
  'getFriendInfoList',
  'getFriendInfoByFriendUserID',
  'batchInsertFriend',
  'getFriendListCount',
  'deleteAllFriend',
  'batchInsertGroupMember',
  'deleteGroupAllMembers',
  'deleteGroupMember',
  'getAllGroupMemberList',
  'getAllGroupMemberUserIDList',
  'getGroupAdminID',
  'getGroupMemberCount',
  'getGroupMemberInfoByGroupIDUserID',
  'getGroupMemberListByGroupID',
  'getGroupMemberListSplit',
  'getGroupMemberListSplitByJoinTimeFilter',
  'getGroupMemberOwner',
  'getGroupMemberOwnerAndAdmin',
  'getGroupMemberUIDListByGroupID',
  'getGroupOwnerAndAdminByGroupID',
  'getGroupSomeMemberInfo',
  'insertGroupMember',
  'searchGroupMembers',
  'updateGroupMember',
  'updateGroupMemberField',
  'getUserJoinedGroupIDs',
  'getGroupMemberListByUserIDs',
  'batchInsertTempCacheMessageList',
  'InsertTempCacheMessage',
  'getAllSingleConversationIDList',
  'getAllConversationIDList',
  'getPageFriendList',
  'getGroupMemberAllGroupIDs',
  'getAlreadyExistSeqList',
  'markConversationAllMessageAsRead',
  'searchAllMessageByContentType',
  'deleteConversationMsgs',
  'markConversationMessageAsRead',
  'markConversationMessageAsReadBySeqs',
  'markDeleteConversationAllMessages',
  'getUnreadMessage',
  'getConversationPeerNormalMsgSeq',
  'getConversationNormalMsgSeq',
  'deleteConversationAllMessages',
  'getMessagesByClientMsgIDs',
  'getMessagesBySeqs',
  'getMessageBySeq',
  'getAllConversations',
  'updateUpload',
  'deleteUpload',
  'getUpload',
  'insertUpload',
  'updateColumnsFriend',
  'searchConversations',
  'getAppSDKVersion',
  'setAppSDKVersion',
  'getVersionSync',
  'setVersionSync',
  'deleteVersionSync',
  'setNotificationSeq',
  'getNotificationAllSeqs',
  'batchInsertNotificationSeq',
  'getExistedTables',
  'getLatestActiveMessage',
  'fileMapSet',
  'fileMapClear',
  'wasmOpen',
  'wasmClose',
  'wasmRead',
];

methods.forEach(name => {
  rpc.registerMethod(name, createStubMethod(name));
});
